// <auto-generated />
using EpiBot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Epibot.Migrations
{
    [DbContext(typeof(EpiBotContext))]
    partial class EpiBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("EpiBot.Models.GitHubTag", b =>
                {
                    b.Property<int>("GitHubTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("GitHubTagId");

                    b.ToTable("GitHubTags");

                    b.HasData(
                        new
                        {
                            GitHubTagId = 1,
                            Email = "hannah@corgibyte.com",
                            Name = "Hannah Young"
                        },
                        new
                        {
                            GitHubTagId = 2,
                            Email = "abminnick@gmail.com",
                            Name = "Aaron Minnick"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
