// <auto-generated />
using System;
using EpiBot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Epibot.Migrations
{
    [DbContext(typeof(EpiBotContext))]
    partial class EpiBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("EpiBot.Models.Byline", b =>
                {
                    b.Property<int>("BylineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("BylineId");

                    b.ToTable("Bylines");
                });

            modelBuilder.Entity("EpiBot.Models.ImportantLink", b =>
                {
                    b.Property<int>("ImportantLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.HasKey("ImportantLinkId");

                    b.ToTable("ImportantLinks");
                });
            modelBuilder.Entity("EpiBot.Models.LoginReminderClient", b =>
                {
                    b.Property<int>("LoginReminderClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAMReminder")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastPMReminder")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("LoginReminderClientId");

                    b.ToTable("LoginReminderClients");
                });

            modelBuilder.Entity("EpiBot.Models.PetNotificationClient", b =>
                {
                    b.Property<int>("PetNotificationClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("PetNotificationClientId");

                    b.ToTable("PetNotificationClients");
                });
#pragma warning restore 612, 618
        }
    }
}
